# Example configuration script
[Main]
seed = 42
n_jobs = 2
folder = "../results/Linear"

# ---------------------------------------------------------------------------#
[Estimator]
model = "LinearRegression"

[Estimator.params]
fit_intercept = false
normalize = true

# ---------------------------------------------------------------------------#
[Grid]
scoring = "r2"
cv = 10
verbose = 0

[Grid.param_grid]
fit_intercept = [true, false]

# ---------------------------------------------------------------------------#
[Data]
path = "../data/matched.npy"

[Data.features]
[Data.features.Mvir]
scaler = "StandardScaler"
log = true
[Data.features.rho0]
scaler = "StandardScaler"
log = true
[Data.features.spin]
scaler = "StandardScaler"
log = true
[Data.features.potential]
scaler = "StandardScaler"
log = false

[Data.target]
[Data.target.MS]
scaler = "StandardScaler"
log = true

[Data.split]
[Data.split.kwargs]
log_target = true
test_size = 0.2
Nbins = 10
n_splits = 50
ax_percentile = [+0.01, +0.99]

# ---------------------------------------------------------------------------#
[Regressor]
[Regressor.permutation_importance]
scoring = "r2"
n_repeats = 5


[Regressor.feature_importance]
n_repeats = 5

[Regressor.learning_curve]
to_calculate = false
train_sizes = [0.1, 0.25, 0.5, 0.75, 1.0]
cv = 5
scoring = "r2"
