[Main]
seed = 42
# Move n_jobs here

[Estimator]
model = "LinearRegression"
params = {"fit_intercept" = false, "normalize" = true}

[Grid]
param_grid = {"fit_intercept" = [true, false]}
scoring = "r2"
n_jobs = 1
cv = 10
verbose = 0

[Data]
path = "../data/matched.npy"

[Data.features]
Mvir = {"scaler" = "QuantileTransformer", "log" = true, kwargs = {"output_distribution" = "normal"}}
# rho0 = {"scaler" = "StandardScaler", "log" = true, kwargs = {}}
# spin = {"scaler" = "StandardScaler", "log" = true, kwargs = {}}
# potential = {"scaler" = "StandardScaler", "log" = false, kwargs = {}}


[Data.target]
MS = {"scaler" = "StandardScaler", "log" = true, kwargs = {}}

[Data.split]
path = "../data/matched.npy"

[Data.split.kwargs]
log_target = true
test_size = 0.2
Nbins = 10
n_splits = 50
ax_percentile = [+0.01, +0.99]

[Regressor]

[Regressor.permutation_importance]

[Regressor.feature_importance]

[Regressor.learning_curve]
